INSERT INTO menu_categories (id, name, slug, description, is_active, sort_order, created_at, updated_at) VALUES 
('cat1', 'Pizzas', 'pizzas', 'Fresh made pizzas', true, 1, NOW(), NOW()),
('cat2', 'Calzones', 'calzones', 'Stuffed calzones', true, 2, NOW(), NOW()),
('cat3', 'Appetizers', 'appetizers', 'Start your meal right', true, 3, NOW(), NOW()),
('cat4', 'Salads', 'salads', 'Fresh and crisp', true, 4, NOW(), NOW()),
('cat5', 'Sandwiches', 'sandwiches', 'Delicious sandwiches', true, 5, NOW(), NOW()),
('cat6', 'Pasta', 'pasta', 'Italian pasta dishes', true, 6, NOW(), NOW()),
('cat7', 'Wings', 'wings', 'Chicken wings', true, 7, NOW(), NOW()),
('cat8', 'Desserts', 'desserts', 'Sweet treats', true, 8, NOW(), NOW()),
('cat9', 'Beverages', 'beverages', 'Drinks and sodas', true, 9, NOW(), NOW()),
('cat10', 'Sides', 'sides', 'Side dishes', true, 10, NOW(), NOW()),
('cat11', 'Specials', 'specials', 'Daily specials', true, 11, NOW(), NOW()),
('cat12', 'Kids Menu', 'kids-menu', 'Kids meals', true, 12, NOW(), NOW()),
('cat13', 'Gluten Free', 'gluten-free', 'Gluten free options', true, 13, NOW(), NOW()),
('cat14', 'Vegetarian', 'vegetarian', 'Vegetarian options', true, 14, NOW(), NOW()),
('cat15', 'Vegan', 'vegan', 'Vegan options', true, 15, NOW(), NOW()),
('cat16', 'Combo Meals', 'combo-meals', 'Value combo meals', true, 16, NOW(), NOW()),
('cat17', 'Family Packs', 'family-packs', 'Family size portions', true, 17, NOW(), NOW()),
('cat18', 'Catering', 'catering', 'Catering options', true, 18, NOW(), NOW());
