services:
  # Next.js Application Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      # This URL must match the credentials in the 'db' service below.
      # The hostname 'db' is the service name defined in this file.
      DATABASE_URL: "postgresql://pizzabuilder:pizzapassword@db:5432/pizzadb"
      # The NEXTAUTH_URL is required for authentication to work correctly in production.
      NEXTAUTH_URL: "http://localhost:3000"
      # A secret is required for JWT signing. Generate a strong one for production.
      NEXTAUTH_SECRET: "your-super-secret-nextauth-secret"
    depends_on:
      db:
        condition: service_healthy
    # This command will run database migrations and then start the app.
    command: sh -c "npx prisma migrate deploy && npm start"

  # PostgreSQL Database Service
  db:
    image: postgres:14-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pizzabuilder -d pizzadb"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: "pizzabuilder"
      POSTGRES_PASSWORD: "pizzapassword"
      POSTGRES_DB: "pizzadb"
    ports:
      - "5432:5432"
    volumes:
      # This named volume will persist the database data across container restarts.
      - postgres_data:/var/lib/postgresql/data

volumes:
  # Define the named volume for data persistence.
  postgres_data:
