# 🚀 STAGING DOCKER COMPOSE
# Staging environment for testing before production deployment

services:
  # ============================================
  # Pizza App - STAGING
  # ============================================
  app-staging:
    build:
      context: .
      dockerfile: Dockerfile.optimized
      target: runner
    container_name: pizza-app-staging
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://${POSTGRES_USER:-pizzauser}:${POSTGRES_PASSWORD:-pizzapass123!}@database:5432/${POSTGRES_DB:-pizzadb_staging}?schema=public
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-staging-secret-key}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3001}
      - GMAIL_USER=${GMAIL_USER}
      - GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}
      - PORT=3000
    ports:
      - "${APP_PORT:-3001}:3000"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - pizza-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # ============================================
  # Use existing database service
  # ============================================
  database:
    external: true
    networks:
      - pizza-network

networks:
  pizza-network:
    external: true

volumes:
  postgres_data:
    external: true
